spring.application.name=mybatis-01-helloworld

# allowMultiQueries=true\u8FD0\u884C\u591A\u4E2Asql\u8BED\u53E5\u6309\u7167\u5206\u53F7\u5206\u5F00\u4E00\u8D77\u6267\u884C\uFF0C\u5C31\u50CF\u4E00\u6B21\u6267\u884C\u4E00\u4E2A\u5927SQL\u8BED\u53E5
spring.datasource.url=jdbc:mysql://localhost:3306/mybatis-example?allowMultiQueries=true
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# \u544A\u8BC9MyBatis,xml\u6587\u4EF6(Mapper\u6587\u4EF6)\u90FD\u5728\u54EA\u91CC
mybatis.mapper-locations=classpath:mapper/**.xml
mybatis.configuration.map-underscore-to-camel-case=true

# \u5F00\u542F\u61D2\u52A0\u8F7D\uFF08\u5EF6\u8FDF\u52A0\u8F7D\uFF09
mybatis.configuration.lazy-loading-enabled=true
# \u4E0B\u9762\u8FD9\u4E2A\u662F\u7ACB\u5373\u52A0\u8F7D\u7684\u610F\u601D\uFF0Cfalse\u8868\u793A\u4E0D\u9A6C\u4E0A\u52A0\u8F7D
mybatis.configuration.aggressive-lazy-loading=false

logging.level.com.atguigu.mybatis.mapper=debug

